[package]
name = "blind_rotate"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.17.0", default-features = false, features = [ "std" ] }
ttfhe = { git = "https://github.com/tremblaythibaultl/ttfhe.git" }
